# Generated by Django 5.1.4 on 2025-01-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
